steps:
  
- id: 'tf apply infraestrutura-rede'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd build-terraform-rede
    terraform init
    terraform destroy -auto-approve
- id: 'tf apply security-rede'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
   cd build-terraform-firewall
   terraform init
   terraform destroy -auto-approve
- id: 'tf apply instancia-frontend'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd build-terraform-compute
    terraform init
    terraform destroy -auto-approve