steps:


# Cluster Prodution#
- id: 'tf apply cluster-Dev-Prod'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd GKE-Prod
    terraform init
    terraform apply -auto-approve


# Cluster Dev-test#
#- id: 'tf apply cluster-Dev-Test'
#  name: 'hashicorp/terraform:1.0.0'
#  entrypoint: 'sh'
#  args: 
#  - '-c'
#  - | 
##    cd Gke-devtest
#    terraform init
 #   terraform apply -auto-approve