steps:

## Deploy arquivos baclend YML
- id: 'Deploy GKE backend'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernets/backend.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mycluster-dev'


## Deploy arquivos baclend YML
- id: 'Deploy GKE Frontend'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernets/frontend.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mycluster-dev'