steps:

## Deploy jenkins server
- id: 'Deploy GKE jenkins server'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernets/jenkins.deployment.yml','--namespace','jenkins']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mycluster-prod'


## Deploy service jenkins
- id: 'Deploy GKE jenkins Service'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernets/jenkis.service.yml','--namespace','jenkins']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mycluster-prod'