FROM openjdk:11-jre-slim

# Variables de entorno de SonarQube
ENV SONARQUBE_HOME=/opt/sonarqube

# Descargar e instalar la versión más reciente de SonarQube
RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget -O /opt/sonarqube.zip https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-latest.zip && \
    unzip /opt/sonarqube.zip -d /opt/ && \
    mv /opt/sonarqube-* $SONARQUBE_HOME && \
    rm /opt/sonarqube.zip && \
    rm -rf $SONARQUBE_HOME/bin/linux-x86-64 && \
    apt-get remove -y wget unzip && \
    apt-get clean

# Exponer el puerto por defecto de SonarQube
EXPOSE 9000

# Iniciar SonarQube
WORKDIR $SONARQUBE_HOME
CMD ["./bin/linux-x86-64/sonar.sh", "start"]