FROM sonarqube:8.9.0-community
RUN apt-get update && apt-get install -y unzip
RUN curl -sSLo /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip && \
    unzip /tmp/sonar-scanner-cli.zip -d /opt && \
    mv /opt/sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner && \
    rm /tmp/sonar-scanner-cli.zip
ENV PATH $PATH:/opt/sonar-scanner/bin
EXPOSE 9000

# Instruções de inicialização
CMD ["./bin/run.sh"]