apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rancher-server
spec:
  template:
    spec:
      containers:
        - image: rancher/server:stable
          ports:
            - containerPort: 8080 # Porta do SonarQube
          resources:
            limits:
              memory: "4Gi" # Limite de memória
              cpu: "2" # Limite de CPU
      autoscaling:
      minScale: 1
      maxScale: 5