apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - image: brunosantos88/awsfrontend:v2
          ports:
            - name: http1
              containerPort: 80