apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  template:
    spec:
      containers:
        - image: sonarsource/sonar-scanner-cli01
          ports:
            - containerPort: 9000 # Porta do SonarQube
          resources:
            limits:
              memory: "4Gi" # Limite de memória
              cpu: "2" # Limite de CPU