apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  template:
    spec:
      containers:
        - image: sonarqube
          ports:
            - containerPort: 9000 # Porta do SonarQube
          resources:
            limits:
              memory: "4Gi" # Limite de memória
              cpu: "2" # Limite de CPU
      autoscaling:
      minScale: 1
      maxScale: 5