apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-crd-install
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-crd-install
          image: 'argoproj/argocd:v2.1.1'  # Use the version you need
          command: ['sh', '-c', 'kubectl apply -n argocd -f /data/manifests/crds; kubectl get crd']
          volumeMounts:
            - name: argocd-crd-install
              mountPath: /data/manifests/crds
          volumes:
          - name: argocd-crd-install
            configMap:
              name: argocd-cm