name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

        # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
         service_account_key: ${{ secrets.GOOGLE_CLOUD_KEY }}
         project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=key.json

      - name: Initialize Terraform
        run: terraform init -reconfigure

      - name: Format Terraform
        run: terraform fmt

      - name: Terraform Apply
        run: terraform apply -auto-approve
