name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

  
      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE CREDENTIAL: ${{ secrets.GOOGLE_CLOUD_KEY }}

      - name: Format Terraform
        run: terraform fmt -check
        env:
          GOOGLE CREDENTIAL: ${{ secrets.GOOGLE_CLOUD_KEY }}


      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE CREDENTIAL: ${{ secrets.GOOGLE_CLOUD_KEY }}
