name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
          cleanup_credentials: false

      - name: Format Terraform
        run: terraform fmt


      - name: Terraform Apply
        run: terraform apply -auto-approve