name: Terraform gcloud 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
          cleanup_credentials: false

      - name: Terraform Iniciar
        run: terraform init

      - name: Format Terraform
        run: terraform fmt

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Copy kube config to GCS
        run: |
          gsutil cp ~/.kube/config gs://${{ secrets.BUCKET_NAME }}/kube-config/config

